name: gps
description: Getting location data in the simplest way, and just getting it. Google service is not used in Android.
version: 0.1.0
author: caijinglong<cjl_spy@163.com>
homepage: https://github.com/caijinglong/flutter_gps

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.gps
    pluginClass: GpsPlugin
